bot:

  # Discord bot's prefix.
  prefix: "ai."

  # AI model for discord bot(openrouter).
  text_model: "google/gemma-2-9b-it:free"

  # MongoDB Connection URI.
  mongodb: "mongodb://localhost:27017/"


api:

  # Port for the FastAPI app.
  port: 6705

  # Discord server ID where the bot will interact with shapes.inc (make sure to use a dummy server).
  api_guild_id: 1253765266115133442

  # Discord server ID, or the support server ID where the verification role is created.
  verify_guild_id: 1144903052717985806

  # The ID of the verified role.
  verified_role_id: 1279261339574861895

  # I think I don't have to explain what it is.
  logging: True

  # Email to send verification emails.
  verification_email: "verify@xet.one"



# If you don't understand, please open a support ticket in our discord server. We will happily help to setup.