"""
Auto-generated list of free models from OpenRouter
Generated by fawom() on 2025-07-16 07:00:51
"""

models = {
    "object": "list",
    "data": [
        
        {
            "id": "agentica-org/deepcoder-14b-preview",
            "object": "model",
            "created": 0,
            "owned_by": "agentica-org",
            "pricing": "free"
        },
        {
            "id": "arliai/qwq-32b-arliai-rpr-v1",
            "object": "model",
            "created": 0,
            "owned_by": "arliai",
            "pricing": "free"
        },
        {
            "id": "cognitivecomputations/dolphin-mistral-24b-venice-edition",
            "object": "model",
            "created": 0,
            "owned_by": "cognitivecomputations",
            "pricing": "free"
        },
        {
            "id": "cognitivecomputations/dolphin3.0-mistral-24b",
            "object": "model",
            "created": 0,
            "owned_by": "cognitivecomputations",
            "pricing": "free"
        },
        {
            "id": "cognitivecomputations/dolphin3.0-r1-mistral-24b",
            "object": "model",
            "created": 0,
            "owned_by": "cognitivecomputations",
            "pricing": "free"
        },
        {
            "id": "deepseek/deepseek-chat",
            "object": "model",
            "created": 0,
            "owned_by": "deepseek",
            "pricing": "free"
        },
        {
            "id": "deepseek/deepseek-chat-v3-0324",
            "object": "model",
            "created": 0,
            "owned_by": "deepseek",
            "pricing": "free"
        },
        {
            "id": "deepseek/deepseek-r1",
            "object": "model",
            "created": 0,
            "owned_by": "deepseek",
            "pricing": "free"
        },
        {
            "id": "deepseek/deepseek-r1-0528",
            "object": "model",
            "created": 0,
            "owned_by": "deepseek",
            "pricing": "free"
        },
        {
            "id": "deepseek/deepseek-r1-0528-qwen3-8b",
            "object": "model",
            "created": 0,
            "owned_by": "deepseek",
            "pricing": "free"
        },
        {
            "id": "deepseek/deepseek-r1-distill-llama-70b",
            "object": "model",
            "created": 0,
            "owned_by": "deepseek",
            "pricing": "free"
        },
        {
            "id": "deepseek/deepseek-r1-distill-qwen-14b",
            "object": "model",
            "created": 0,
            "owned_by": "deepseek",
            "pricing": "free"
        },
        {
            "id": "deepseek/deepseek-v3-base",
            "object": "model",
            "created": 0,
            "owned_by": "deepseek",
            "pricing": "free"
        },
        {
            "id": "featherless/qwerky-72b",
            "object": "model",
            "created": 0,
            "owned_by": "featherless",
            "pricing": "free"
        },
        {
            "id": "google/gemini-2.0-flash-exp",
            "object": "model",
            "created": 0,
            "owned_by": "google",
            "pricing": "free"
        },
        {
            "id": "google/gemini-2.5-pro-exp-03-25",
            "object": "model",
            "created": 0,
            "owned_by": "google",
            "pricing": "free"
        },
        {
            "id": "google/gemma-2-9b-it",
            "object": "model",
            "created": 0,
            "owned_by": "google",
            "pricing": "free"
        },
        {
            "id": "google/gemma-3-12b-it",
            "object": "model",
            "created": 0,
            "owned_by": "google",
            "pricing": "free"
        },
        {
            "id": "google/gemma-3-27b-it",
            "object": "model",
            "created": 0,
            "owned_by": "google",
            "pricing": "free"
        },
        {
            "id": "google/gemma-3-4b-it",
            "object": "model",
            "created": 0,
            "owned_by": "google",
            "pricing": "free"
        },
        {
            "id": "google/gemma-3n-e2b-it",
            "object": "model",
            "created": 0,
            "owned_by": "google",
            "pricing": "free"
        },
        {
            "id": "google/gemma-3n-e4b-it",
            "object": "model",
            "created": 0,
            "owned_by": "google",
            "pricing": "free"
        },
        {
            "id": "meta-llama/llama-3.1-405b-instruct",
            "object": "model",
            "created": 0,
            "owned_by": "meta-llama",
            "pricing": "free"
        },
        {
            "id": "meta-llama/llama-3.2-11b-vision-instruct",
            "object": "model",
            "created": 0,
            "owned_by": "meta-llama",
            "pricing": "free"
        },
        {
            "id": "meta-llama/llama-3.2-3b-instruct",
            "object": "model",
            "created": 0,
            "owned_by": "meta-llama",
            "pricing": "free"
        },
        {
            "id": "meta-llama/llama-3.3-70b-instruct",
            "object": "model",
            "created": 0,
            "owned_by": "meta-llama",
            "pricing": "free"
        },
        {
            "id": "microsoft/mai-ds-r1",
            "object": "model",
            "created": 0,
            "owned_by": "microsoft",
            "pricing": "free"
        },
        {
            "id": "mistralai/devstral-small-2505",
            "object": "model",
            "created": 0,
            "owned_by": "mistralai",
            "pricing": "free"
        },
        {
            "id": "mistralai/mistral-7b-instruct",
            "object": "model",
            "created": 0,
            "owned_by": "mistralai",
            "pricing": "free"
        },
        {
            "id": "mistralai/mistral-nemo",
            "object": "model",
            "created": 0,
            "owned_by": "mistralai",
            "pricing": "free"
        },
        {
            "id": "mistralai/mistral-small-24b-instruct-2501",
            "object": "model",
            "created": 0,
            "owned_by": "mistralai",
            "pricing": "free"
        },
        {
            "id": "mistralai/mistral-small-3.1-24b-instruct",
            "object": "model",
            "created": 0,
            "owned_by": "mistralai",
            "pricing": "free"
        },
        {
            "id": "mistralai/mistral-small-3.2-24b-instruct",
            "object": "model",
            "created": 0,
            "owned_by": "mistralai",
            "pricing": "free"
        },
        {
            "id": "moonshotai/kimi-dev-72b",
            "object": "model",
            "created": 0,
            "owned_by": "moonshotai",
            "pricing": "free"
        },
        {
            "id": "moonshotai/kimi-k2",
            "object": "model",
            "created": 0,
            "owned_by": "moonshotai",
            "pricing": "free"
        },
        {
            "id": "moonshotai/kimi-vl-a3b-thinking",
            "object": "model",
            "created": 0,
            "owned_by": "moonshotai",
            "pricing": "free"
        },
        {
            "id": "nousresearch/deephermes-3-llama-3-8b-preview",
            "object": "model",
            "created": 0,
            "owned_by": "nousresearch",
            "pricing": "free"
        },
        {
            "id": "nvidia/llama-3.1-nemotron-ultra-253b-v1",
            "object": "model",
            "created": 0,
            "owned_by": "nvidia",
            "pricing": "free"
        },
        {
            "id": "qwen/qwen-2.5-72b-instruct",
            "object": "model",
            "created": 0,
            "owned_by": "qwen",
            "pricing": "free"
        },
        {
            "id": "qwen/qwen-2.5-coder-32b-instruct",
            "object": "model",
            "created": 0,
            "owned_by": "qwen",
            "pricing": "free"
        },
        {
            "id": "qwen/qwen2.5-vl-32b-instruct",
            "object": "model",
            "created": 0,
            "owned_by": "qwen",
            "pricing": "free"
        },
        {
            "id": "qwen/qwen2.5-vl-72b-instruct",
            "object": "model",
            "created": 0,
            "owned_by": "qwen",
            "pricing": "free"
        },
        {
            "id": "qwen/qwen3-14b",
            "object": "model",
            "created": 0,
            "owned_by": "qwen",
            "pricing": "free"
        },
        {
            "id": "qwen/qwen3-235b-a22b",
            "object": "model",
            "created": 0,
            "owned_by": "qwen",
            "pricing": "free"
        },
        {
            "id": "qwen/qwen3-30b-a3b",
            "object": "model",
            "created": 0,
            "owned_by": "qwen",
            "pricing": "free"
        },
        {
            "id": "qwen/qwen3-32b",
            "object": "model",
            "created": 0,
            "owned_by": "qwen",
            "pricing": "free"
        },
        {
            "id": "qwen/qwen3-4b",
            "object": "model",
            "created": 0,
            "owned_by": "qwen",
            "pricing": "free"
        },
        {
            "id": "qwen/qwen3-8b",
            "object": "model",
            "created": 0,
            "owned_by": "qwen",
            "pricing": "free"
        },
        {
            "id": "qwen/qwq-32b",
            "object": "model",
            "created": 0,
            "owned_by": "qwen",
            "pricing": "free"
        },
        {
            "id": "rekaai/reka-flash-3",
            "object": "model",
            "created": 0,
            "owned_by": "rekaai",
            "pricing": "free"
        },
        {
            "id": "sarvamai/sarvam-m",
            "object": "model",
            "created": 0,
            "owned_by": "sarvamai",
            "pricing": "free"
        },
        {
            "id": "shisa-ai/shisa-v2-llama3.3-70b",
            "object": "model",
            "created": 0,
            "owned_by": "shisa-ai",
            "pricing": "free"
        },
        {
            "id": "tencent/hunyuan-a13b-instruct",
            "object": "model",
            "created": 0,
            "owned_by": "tencent",
            "pricing": "free"
        },
        {
            "id": "thudm/glm-4-32b",
            "object": "model",
            "created": 0,
            "owned_by": "thudm",
            "pricing": "free"
        },
        {
            "id": "thudm/glm-z1-32b",
            "object": "model",
            "created": 0,
            "owned_by": "thudm",
            "pricing": "free"
        },
        {
            "id": "tngtech/deepseek-r1t-chimera",
            "object": "model",
            "created": 0,
            "owned_by": "tngtech",
            "pricing": "free"
        },
        {
            "id": "tngtech/deepseek-r1t2-chimera",
            "object": "model",
            "created": 0,
            "owned_by": "tngtech",
            "pricing": "free"
        }
    ]
}
